# Generated by Django 5.1.3 on 2024-11-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_alter_redeemeditem_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemeditem',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
